### ISSUE TITLE
Ingress using Traefil

### ISSUE THREAD

**Issue by ekarlso** [upmc-enterprises/elasticsearch-operator#159]
How can we configure traefik ln k8s to connect to kibana thst has https?

**Comment by pieterlange** [comment]
Not supported natively in the operator yet, but you can manually update the kibana deployment with the following environment variable in order to front it with an SSL offloading loadbalancer:
```
    - name: SERVER_SSL_ENABLED
      value: "false"
```

**Comment by max-lobur** [comment]
If you run a set of ingress controllers for ELK you can use ingress annotations:
```
    nginx.ingress.kubernetes.io/secure-backends: 'true'  # Hack for https://github.com/upmc-enterprises/elasticsearch-operator/issues/159
    nginx.ingress.kubernetes.io/server-snippet: "proxy_ssl_verify off;"  # Cert is in elk namespace - not reachable from ingress. So ignoring for now.
```
Or, if you're lucky to run ingress controller in the same namespace with ELK, instead of server-snipped you can use annotation that points to kibana cert: `nginx.ingress.kubernetes.io/secure-verify-ca-secret`

Docs: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#secure-backends

**Comment by stevesloka** [comment]
There's another issue to add auth, once we get that merged I hope to have some good examples of how to better manage auth with Kibana, etc. 

See: #221
