### ISSUE TITLE
storage-class is ignored 

### ISSUE THREAD

**Issue by wjimenez5271** [upmc-enterprises/elasticsearch-operator#169]
given the following keys in my `ElasticsearchCluster` resource:

```
  storage:
    storage-class: io-optimized-block
```

It seems the operator ignores this value and tries to create its own SC with the name "us-west-2":

```
time="2018-04-03T20:31:40Z" level=info msg="StorageClass us-west-2c not found, creating..."
time="2018-04-03T20:31:40Z" level=error msg="Could not create storage class: StorageClass.storage.k8s.io \"us-west-2c\" is invalid: provisioner: Required value"
time="2018-04-03T20:31:40Z" level=error msg="Error creating storage class StorageClass.storage.k8s.io \"us-west-2c\" is invalid: provisioner: Required value"
time="2018-04-03T20:31:40Z" level=error msg="StorageClass.storage.k8s.io \"us-west-2c\" is invalid: provisioner: Required value"
```

Not sure if I am missing a setting somewhere...

**Comment by wjimenez5271** [comment]
Figured it out, the `zones` field needs to be set to `[]` like so
```
  zones: []
```

**Comment by Sneko** [comment]
Same error because I was setuping zones+storageClass 👎 

`helm install --name=elasticsearch es-operator/elasticsearch --set kibana.enabled=True --set cerebro.enabled=True --set storage.class=slow --set zones="{us-central1-a,us-central1-b}" --namespace logging`

I was just needed storageClass since zones are defined inside:

`helm install --name=elasticsearch es-operator/elasticsearch --set kibana.enabled=True --set cerebro.enabled=True --set storage.class=slow --namespace logging`

Hope it will help someone 😄

**Comment by stevesloka** [comment]
Thanks for the tips @sneko
