### ISSUE TITLE
Support creation of multiple clusters

### ISSUE THREAD

**Issue by splisson-altair** [upmc-enterprises/elasticsearch-operator#51]
Correct me if I'm wrong but currently the operator creates only one cluster with non-scoped names ie 'svc/elasticsearch'
When creating new elasticsearchcluster resources, the operator detects them but nothing happens

**Comment by stevesloka** [comment]
Yeah this a problem currently which was referenced in #15. Originally I was using `kubectl proxy` from inside the pod to get access to the TPR api, but since have upgraded to use `client-go` and removed the proxy bit. 

It's on my current list to deploy a single operator, and allow clusters to be gen'd in any namespace. Also, I want to add the ability to put prefixes on clusters, so you could run multiple in the same namespace.

**Comment by splisson-altair** [comment]
Ok, I ll use namespace for now. I also implemented a first version that uses the clusterName as prefix for the services names and component. I have not tested it yet. If it's decent I'll submit a pull request.

**Comment by stevesloka** [comment]
Closed by #52
