### ISSUE TITLE
docker-elasticsearch-kubernetes:5.3.1_2

### ISSUE THREAD

**Issue by FaKod** [upmc-enterprises/elasticsearch-operator#55]
Default Image does not work for me..

getting:

Error injecting constructor, com.timgroup.statsd.StatsDClientException: Failed to start StatsD client
  at com.automattic.elasticsearch.statsd.StatsdService.<init>(Unknown Source)
  while locating com.automattic.elasticsearch.statsd.StatsdService

**Comment by stevesloka** [comment]
You need a statsd cluster running to use this image when it's not there it breaks. I just updated the default image to not use this tag since people keep hitting this and its hard to get started since you wouldn't know of these deps. Alternatively, you can also override the base image in the TPR. See #34
